### ISSUE TITLE
Load Live Data

### ISSUE THREAD

**Issue by MotionPhix** [stack-stark/ngx-g2plot#1]
From the examples you show, you're loading static data that's already within the component... Please show an example where data is loaded live from the server. I have tried it myself and it gives me a lot of errors

**Comment by stack-stark** [comment]
Sorry, I neglected to redraw the problem, it is a serious bug and I will fix it in the near future

**Comment by MotionPhix** [comment]
I managed to load Live data and it's working fine now... (basically I
declared all the options outside ngOninit then load the options.data in
ngOninit after fetching data from the backend)
