### ISSUE TITLE
请教一下, 这个库解决了什么问题?

### ISSUE THREAD

**Issue by Eve-Sama** [stack-stark/ngx-g2plot#10]
因为自己的Angular项目也在使用g2plot, 是可以正常使用的. 偶然间在g2plot官网看到这个项目, 但是我没看懂这个库解决了什么问题? 纯属好奇问一下

**Comment by stack-stark** [comment]
这个库只是二次封装了一下，这样可以通过指令的方式使用对应的图表。g2plot本身与前端框架无关，对应框架的二次封装只是为了方便使用 @Eve-Sama

**Comment by Eve-Sama** [comment]
我看了下demo
   
    <div starkG2plotLine  #divG2plotLine="g2plotLine" [options]="options"></div>

那假如我需要根据一个`chartType`字段来决定生成不同类型的图表, 在g2plot中我是new不同类型的图表. 在ngx-g2plot中我则是要写不同的ngIf来判断使用哪个模板?  是这样的么?

**Comment by stack-stark** [comment]
恩 如果是你提的这种情况的话，得写一大堆div和指令再配合 ngif来处理。但是这样繁琐还显得不优雅，我这两天看看有没有更优雅的方式来实现你所说的这种情况。或者你有没有啥好的建议

**Comment by Eve-Sama** [comment]
没有别的办法. 而这个需求是很常见的, 使用图表不可能只使用一种图. 在G2plot种把判断逻辑写在ts中. 在ngx-g2plot中则是把判断逻辑写在html上, 二者本身在使用上没有太大区别. 因为在这个场景下我没有足够的动力去使用ngx-g2plot, 所以才提个issue问下是解决了什么问题. 非常感谢回答.
